### ISSUE TITLE
Too much logging

### ISSUE THREAD

**Issue by ctdk** [raintank/graphite-api#3]
graphite-api's got logging now, which is great, but now it's always logging at the debug level, and there doesn't seem to be a setting right now to adjust that. It did remind me that that needs to be added to logrotate, but we should also have a setting to adjust the logging level there. Already it's getting kind of out of hand.

**Comment by woodsaj** [comment]
just need to add the following to /etc/graphite-api.yaml

```
logging:
  version: 1
  handlers:
    raw:
      level: INFO
      class: logging.StreamHandler
      formatter: raw
  loggers:
    root:
      handlers:
        - raw
      level: INFO
      propagate: false
    graphite_api:
      handlers:
        - raw
      level: INFO
```
